export const routes = {
    home: "/",
    default: "/",
    singin: "/sign/in",
    register: "/register",
    productParam: "id",
    product: "/product:",
    profile: "/data/entry/profile",
    checkout: "/checkout",
    orders: "/orders",
    adminOrders: "/sales/orders",
    settings: "/settings",
    deliveryOptions: "/checkout/options",
    productsEdit: "/products/edit",
}